name: CI

on:
  push:
    branches:
    - Epreuve3
    #- main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  empty-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
    
  deploy-dev:
    environment: dev
    needs: prepare
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    - name: Set required PowerShell modules
      id: psmodulecache
      uses: potatoqualitee/psmodulecache@v1
      with:
        modules-to-cache: Az
    - name: Setup PowerShell module cache
      id: cacher
      uses: actions/cache@v2
      with:
        path: ${{ steps.psmodulecache.outputs.modulepath }}
        key: ${{ steps.psmodulecache.outputs.keygen }}

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true

    - name: Deploy Azure resources
      env: 
        AZURE_RG_NAME: ${{ secrets.AZURE_RG_NAME }}
      shell: pwsh
      run: |
        .\Calicot\Calicot-IaC\Deploy-AzureResourceGroup.ps1 -ResourceGroupName "$env:AZURE_RG_NAME" -ResourceGroupLocation ${{secrets.AZURE_RG_LOCATION}}