name: CI

on:
  push:
    branches:
    - Epreuve4
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  prepare:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    # Setting up required powershell modules
    - name: Set required PowerShell modules
      id: psmodulecache
      uses: potatoqualitee/psmodulecache@v1
      with:
        modules-to-cache: Az, Pester
      
    # Setting up the powershell module cache
    - name: Setup PowerShell module cache
      id: cacher
      uses: actions/cache@v2
      with:
        path: ${{ steps.psmodulecache.outputs.modulepath }}
        key: ${{ steps.psmodulecache.outputs.keygen }}
        
    # Installing the required powershell module, if not cached
    - name: Install required PowerShell modules
      if: steps.cacher.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module ${{ steps.psmodulecache.outputs.needed }} -ErrorAction Stop -Force -Verbose -AllowClobber

  deploy-dev:
    environment: dev
    needs: prepare
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    - name: Set required PowerShell modules
      id: psmodulecache
      uses: potatoqualitee/psmodulecache@v1
      with:
        modules-to-cache: Az
    - name: Setup PowerShell module cache
      id: cacher
      uses: actions/cache@v2
      with:
        path: ${{ steps.psmodulecache.outputs.modulepath }}
        key: ${{ steps.psmodulecache.outputs.keygen }}

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true

    - name: Deploy Azure resources
      env: 
        AZURE_RG_NAME: ${{ secrets.AZURE_RG_NAME }}
      shell: pwsh
      run: |
        .\Calicot\Calicot-IaC\Deploy-AzureResourceGroup.ps1 -ResourceGroupName "$env:AZURE_RG_NAME" -ResourceGroupLocation ${{secrets.AZURE_RG_LOCATION}}

    - name: Test if Azure resources are deployed successfully
      env: 
        AZURE_RG_NAME: ${{ secrets.AZURE_RG_NAME }}
        AZURE_RG_LOCATION: ${{ secrets.AZURE_RG_LOCATION }}
      shell: pwsh
      run: |
         Invoke-Pester .\Calicot\Calicot-IaC\Deploy-AzureResourceGroup.Tests.ps1 -Output Detailed

  deploy-accept:
    environment: accept
    needs: deploy-dev
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    - name: Set required PowerShell modules
      id: psmodulecache
      uses: potatoqualitee/psmodulecache@v1
      with:
        modules-to-cache: Az
    - name: Setup PowerShell module cache
      id: cacher
      uses: actions/cache@v2
      with:
        path: ${{ steps.psmodulecache.outputs.modulepath }}
        key: ${{ steps.psmodulecache.outputs.keygen }}

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true

    - name: Deploy Azure resources
      env: 
        AZURE_RG_NAME: ${{ secrets.AZURE_RG_NAME }}
      shell: pwsh
      run: |
        .\Calicot\Calicot-IaC\Deploy-AzureResourceGroup.ps1 -ResourceGroupName "$env:AZURE_RG_NAME" -ResourceGroupLocation ${{secrets.AZURE_RG_LOCATION}}

    - name: Test if Azure resources are deployed successfully
      env: 
        AZURE_RG_NAME: ${{ secrets.AZURE_RG_NAME }}
        AZURE_RG_LOCATION: ${{ secrets.AZURE_RG_LOCATION }}
      shell: pwsh
      run: |
         Invoke-Pester .\Calicot\Calicot-IaC\Deploy-AzureResourceGroup.Tests.ps1 -Output Detailed

  deploy-prod:
    environment: prod
    needs: deploy-accept
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    - name: Set required PowerShell modules
      id: psmodulecache
      uses: potatoqualitee/psmodulecache@v1
      with:
        modules-to-cache: Az
    - name: Setup PowerShell module cache
      id: cacher
      uses: actions/cache@v2
      with:
        path: ${{ steps.psmodulecache.outputs.modulepath }}
        key: ${{ steps.psmodulecache.outputs.keygen }}

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true

    - name: Deploy Azure resources
      env: 
        AZURE_RG_NAME: ${{ secrets.AZURE_RG_NAME }}
      shell: pwsh
      run: |
        .\Calicot\Calicot-IaC\Deploy-AzureResourceGroup.ps1 -ResourceGroupName "$env:AZURE_RG_NAME" -ResourceGroupLocation ${{secrets.AZURE_RG_LOCATION}}

    - name: Test if Azure resources are deployed successfully
      env: 
        AZURE_RG_NAME: ${{ secrets.AZURE_RG_NAME }}
        AZURE_RG_LOCATION: ${{ secrets.AZURE_RG_LOCATION }}
      shell: pwsh
      run: |
         Invoke-Pester .\Calicot\Calicot-IaC\Deploy-AzureResourceGroup.Tests.ps1 -Output Detailed
