name: CI

on:
  push:
    branches:
    - Epreuve2

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: .\Calicot\Calicot-IaC\Deploy-AzureResourceGroup.ps1 -ResourceGroupName azchallenge-hallani-dev-rg
      shell: powershell
